name: secretaria_app
description: Aplicativo mobile da secretaria acadêmica

environment:
  sdk: '^3.6.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.1
  provider: ^6.1.2
  flutter_svg: ^2.0.10+1

flutter:
  uses-material-design: true
